### PR TITLE
Request to merge Active record Feature branch to development

### PR DESCRIPTION
**Pull request by SunilDevalla**
A project consists of ActiveRecord to make a micro-reddit with users, posts, and comments.

### CODE REVIEW

**Review by MkrtichSargsyan — COMMENTED** [review]
## _Status:_ Invalid submission warning

## Hello Guys


This Code Review Request will be marked as invalid in your Dashboard because the actions on Github were not set up properly.

Please make the necessary changes and submit another code review request once you are ready! :slightly_smiling_face:.


> ps: . If you have any questions about my review or need help, you can message me on slack ( @mkrtichsargsyan )

**Comment by SunilDevalla** [comment]
Thanks for the review @MkrtichSargsyan ... I have added the git-flow as mentioned, please let me know of any further changes required...Thank you...

**Review by MkrtichSargsyan — CHANGES_REQUESTED** [review]
## _Status:_ Changes Requested :recycle:

## Hello Sunil Devalla

THIS IS VERY IMPRESSIVE WORK. YOU HAVE DONE A GOOD JOB :+1:
However, there are some changes that you need to make in order to get your project approved

- [x] Make ```development``` as the main branch

- [x] Add validation for comments 

    >validates :body, presence: true

<hr>

## OPTIONAL

- [x] Add  ```dependent: :destroy```  for comments and posts, so when the user delete any post all the comments related to that post could be deleted

      has_many :comments, dependent: :destroy (post.rb file)
      has_many :posts, dependent: :destroy   (user.rb file)

> ps: . If you have any questions about my review or need help, you can message me on slack ( @mkrtichsargsyan )

**Comment by SunilDevalla** [comment]
Thanks for the Quick and helpful review again @MkrtichSargsyan, I appreciate it. Made changes as suggested.

**Review by mke2111 — APPROVED** [review]
# 😄 🥇  STATUS: APPROVED  🥇 👏🏽 

## Hey Happy Coder, 👋🏽 
Congratulations, 🥂 . You got minimum requirements for approval. 👍🏽 

### **_Well Done_** 💯 

    1. The app runs as expected

### **_Room for Improvement_** 🤪 

    1. You may choose to keep your code clean and apply the DRY rule.
        `validates :title, :body, presence: true` in the Post model.
        `validates :username, :password, presence: true` in the User model.


### You may now merge to the develop branch and remember to submit a project completion form.
### I wish you the very best in your upcoming projects.

**Cheers 🍹 and Happy coding 💻** 

<hr>

### Best regards
Slack 🆘  Roy Mukuye
Twitter 🐦  [Roy Mukuye](https://twitter.com/Roymkenya)
LinkedIn 🔗  [Roy Mukuye](https://www.linkedin.com/in/roy-mukuye/)

**Pull request merged**
